- README.md
- dashboards/README.md
- runbooks/README.md
- runbooks/VirtAPIDown.md
Added README.md files to the dashboards and
runbooks directories and updated the main README.md.
Added the first runbook for VirtAPIDown alert.
> Create dashboards and runbooks directories and a runbook example

- runbooks/KubevirtHyperconvergedClusterOperatorCRModification.md
Signed-off-by: Erkan Erol <eerol@redhat.com>
> Add runbook for KubevirtHyperconvergedClusterOperatorCRModification

- runbooks/OrphanedVirtualMachineImages.md
Adds the runbook for the OrphanedVirtualMachineImages alert.
> Add OrphanedVirtualMachineImages runbook

- runbooks/OutdatedVirtualMachineInstanceWorkloads.md
This handles the `OutdatedVirtualMachineInstanceWorkloads` alert
> add runbook for outdated vmi workloads alert

- runbooks/KubevirtHyperconvergedClusterOperatorCRModification.md
Signed-off-by: Erkan Erol <eerol@redhat.com>
> Update component_name label for KubevirtHyperconvergedClusterOperatorCRModification

- dashboards/kubevirt-top-consumers.json
> Add initial top consumers dashhboard

- runbooks/LowKVMNodesCount.md
Signed-off-by: Andrey Odarenko <andreyo@il.ibm.com>
> Create runbook for LowKVMNodesCount alert

- runbooks/KubevirtHyperconvergedClusterOperatorUSModification.md
Add new HCO alert KubevirtHyperconvergedClusterOperatorUSModification to notify when using the jsonpatch annotations.
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
> Add new HCO alert KubevirtHyperconvergedClusterOperatorUSModification

- runbooks/KubeVirtComponentExceedsRequestedCPU.md
- runbooks/KubeVirtComponentExceedsRequestedMemory.md
Signed-off-by: Ashley Schuett <aschuett@redhat.com>
> add runbooks for Memory and CPU request alerts

- runbooks/KubevirtVmHighMemoryUsage.md
Signed-off-by: Andrey Odarenko <andreyo@il.ibm.com>
> Create runbook for KubevirtVmHighMemoryUsage alert

- docs/runbooks/CnaoNotReady.md
- docs/runbooks/README.md
This PR adds the CnaoNotReady alert runbook
> runbooks, Add CnaoNotReady alert

- docs/runbooks/CnaoNotReady.md
Signed-off-by: Ram Lavi <ralavi@redhat.com>
> runbooks, Add info on CnaoNotReady runbook

- docs/runbooks/CnaoDown.md
- docs/runbooks/README.md
This PR adds the CnaoDown alert runbook
> runbooks, Add CnaoDown Alert 

- docs/runbooks/NetworkAddonsConfigNotReady.md
- docs/runbooks/README.md
Signed-off-by: Ram Lavi <ralavi@redhat.com>
> runbooks, rename CnaoNotReady alert to NetworkAddonsConfigNotReady

- dashboards/kubevirt-top-consumers.json
OCP Ui doesn't support all of Grafana's features.
I tweaked the dashboard json, so it will show up
in the UI as expected.
> Update top consumers dashboard based on OCP limitations

- docs/runbooks/KubeMacPoolDuplicateMacsFound.md
- docs/runbooks/README.md
Signed-off-by: Or Shoval <oshoval@redhat.com>
> runbooks, Add info about KubeMacPoolDuplicateMacsFound runbook

- docs/runbooks/SSPOperatorDown.md
Signed-off-by: borod108 <boris.od@gmail.com>
> Fix text in SSPOperatorDown runbook

- docs/runbooks/README.md
- docs/runbooks/SSPFailingToReconcile.md
Signed-off-by: borod108 <boris.od@gmail.com>
> Add runbook for SSPFailingToReconcile alert

- monitoring-guidelines.md
> Add monitoring guidelines

- docs/runbooks/NoReadyVirtController.md
- docs/runbooks/README.md
> Add runbook for NoReadyVirtController alert

- docs/runbooks/LowReadyVirtControllersCount.md
- docs/runbooks/README.md
> Add runbook for LowReadyVirtControllersCount alert

- docs/runbooks/LowVirtAPICount.md
- docs/runbooks/README.md
> Add runbook for LowVirtAPICount alert

- docs/runbooks/KubeVirtComponentExceedsRequestedMemory.md
Signed-off-by: Erkan Erol eerol@redhat.com
> Fix typo in title

- docs/runbooks/CDIDataVolumeUnusualRestartCount.md
- docs/runbooks/CDINotReady.md
- docs/runbooks/CDIOperatorDown.md
- docs/runbooks/README.md
- CDIOperatorDown
- CDINotReady
- CDIDataVolumeUnusualRestartCount
> Add initial 3 CDI alert runbooks

- docs/runbooks/HPPNotReady.md
- docs/runbooks/HPPOperatorDown.md
- docs/runbooks/README.md
- HPPOperatorDown
- HPPNotReady
> Add initial HPP alert runbooks

- docs/runbooks/KubeMacPoolDown.md
- docs/runbooks/README.md
Signed-off-by: Ram Lavi <ralavi@redhat.com>
> docs, Add runbook for KubeMacPoolDown

- docs/runbooks/README.md
- docs/runbooks/VirtControllerRESTErrorsHigh.md
> Add runbook for VirtControllerRESTErrorsHigh alert

- docs/runbooks/README.md
- docs/runbooks/VirtControllerRESTErrorsBurst.md
> Add runbook for VirtControllerRESTErrorsBurst alert

- docs/runbooks/README.md
- docs/runbooks/VirtHandlerRESTErrorsHigh.md
> Add runbook for VirtHandlerRESTErrorsHigh alert

- docs/runbooks/README.md
- docs/runbooks/VirtHandlerRESTErrorsBurst.md
> Add runbook for VirtHandlerRESTErrorsBurst alert

- docs/runbooks/LowVirtControllersCount.md
- docs/runbooks/README.md
> Add runbook for LowVirtControllersCount alert

- docs/runbooks/README.md
- docs/runbooks/VirtControllerDown.md
> Add runbook for VirtControllerDown alert

- docs/runbooks/SSPCommonTemplatesModificationReverted.md
- docs/runbooks/SSPFailingToReconcile.md
- docs/runbooks/SSPHighRateRejectedVms.md
- docs/runbooks/SSPOperatorDown.md
- docs/runbooks/SSPTemplateValidatorDown.md
Add improvements for the diagnostics section in SSPCommonTemplatesModificationReverted.
Also improve instructions to use logs in other runbooks.
Signed-off-by: borod108 <boris.od@gmail.com>
> Improve SSPCommonTemplatesModificationReverted diagnostics

- docs/runbooks/README.md
- docs/runbooks/VirtApiRESTErrorsBurst.md
- docs/runbooks/VirtApiRESTErrorsHigh.md
Add runbook for VirtApiRESTErrorsHigh and VirtApiRESTErrorsBurst alerts
Addresses the following issue: https://github.com/kubevirt/kubevirt/issues/6491
> Add runbook for VirtApiRESTErrorsHigh and VirtApiRESTErrorsBurst alerts

- docs/runbooks/KubevirtVmHighMemoryUsageBasedOnRequests.md
- docs/runbooks/README.md
> Add a runbook for KubevirtVmHighMemoryUsageBasedOnRequests

- OWNERS_ALIASES
Signed-off-by: Erkan Erol eerol@redhat.com
> Remove Erkan from Owners

- .github/workflows/update_metrics_docs.yaml
Signed-off-by: João Vilaça <jvilaca@redhat.com>
> Add GitHub Action to keep metrics documentation file updated

- monitoring-guidelines.md
> Fix issues in the monitoring-guideline document

- dashboards/openshift/kubevirt-top-consumers.json
> Fix issues in top consumers dashboard

- docs/runbooks/CDIDataImportCronOutdated.md
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>
> Manual stuck DV deletion needed after setting default storage class 

- docs/runbooks/CnaoNmstateMigration.md
- docs/runbooks/README.md
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
> Add runbook explaining CnaoNmstateMigration alert

- monitoring-guidelines.md
Added priority and infra_alert labels.
> Add priority and infra_alert labels

- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
- docs/runbooks/KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert.md
- docs/runbooks/README.md
Signed-off-by: orenc1 <ocohen@redhat.com>
> Add a Runbook for KubeVirtVMIExcessiveMigrations alert

- docs/runbooks/KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert.md
Editing runbook in preparation for publishing downstream.
> Editing KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert

- docs/runbooks/KubeMacPoolDown.md
> TW review of KubeMacPoolDown

- docs/runbooks/KubevirtHyperconvergedClusterOperatorCRModification.md
> Edit KubevirtHyperconvergedClusterOperatorCRModification

- docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> Edit KubeMacPoolDuplicateMacsFound

- docs/runbooks/KubeMacPoolDown.md
> Kube mac pool down update

- docs/runbooks/SSPFailingToReconcile.md
> SSPFailingToReconcile edits

- docs/runbooks/SSPTemplateValidatorDown.md
> Edit SSPTemplateValidatorDown

- docs/runbooks/VirtAPIDown.md
> VirtAPIDown updates

- docs/runbooks/KubevirtHyperconvergedClusterOperatorUSModification.md
> KubevirtHyperconvergedClusterOperatorUSModification edits

- docs/runbooks/CDIDataVolumeUnusualRestartCount.md
> CDIDataVolumeUnusualRestartCount edits

- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
> KubeVirtVMIExcessiveMigrations edits

- docs/runbooks/SSPFailingToReconcile.md
Update SSPFailingToReconcile meaning, explained what does the SSP operator do.
Signed-off-by: ShirlyRadco [sradco@redhat.com](mailto:sradco@redhat.com)
> Update SSPFailingToReconcile meaning

- docs/runbooks/SSPOperatorDown.md
> Edit SSPOperatorDown

- docs/runbooks/KubeMacPoolDuplicateMacsFound.md
- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
- docs/runbooks/SSPHighRateRejectedVms.md
> Fixing code block indents

- docs/runbooks/OrphanedVirtualMachineInstances.md
> OrphanedVirtualMachineInstances edits

- docs/runbooks/VirtHandlerDaemonSetRolloutFailing.md
> VirtHandlerDaemonSetRolloutFailing edits

- docs/runbooks/CDIDataVolumeUnusualRestartCount.md
- docs/runbooks/KubeMacPoolDown.md
- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
- docs/runbooks/KubevirtHyperconvergedClusterOperatorUSModification.md
- docs/runbooks/OrphanedVirtualMachineInstances.md
- docs/runbooks/SSPFailingToReconcile.md
- docs/runbooks/SSPOperatorDown.md
- docs/runbooks/SSPTemplateValidatorDown.md
- docs/runbooks/VirtAPIDown.md
Changing CNV to DS and KV to US, so that the conversion script is more generic.
> Updates for upstream/downstream

- docs/runbooks/KubevirtVmHighMemoryUsage.md
> KubevirtVmHighMemoryUsage edits

- docs/runbooks/CDINotReady.md
Signed-off-by: davozeni <davozeni@redhat.com>
I've edited the runbook for downstream conversion.
> Edited the CDINotReady runbook

- docs/runbooks/VirtOperatorRESTErrorsBurst.md
- docs/runbooks/VirtOperatorRESTErrorsHigh.md
Signed-off-by: Jiří Herrmann <jherrman@redhat.com>
> Updates to VirtOperatorRESTErrors* docs

- docs/runbooks/HPPOperatorDown.md
@apinnick please take a look when you have a bit of time
> Doc update to HPPOperatorDown

- docs/runbooks/CnaoDown.md
- docs/runbooks/KubeMacPoolDown.md
- docs/runbooks/KubeMacPoolDuplicateMacsFound.md
- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
- docs/runbooks/KubevirtVmHighMemoryUsage.md
- docs/runbooks/OrphanedVirtualMachineInstances.md
- docs/runbooks/SSPFailingToReconcile.md
- docs/runbooks/SSPHighRateRejectedVms.md
- docs/runbooks/SSPOperatorDown.md
- docs/runbooks/SSPTemplateValidatorDown.md
- docs/runbooks/VirtAPIDown.md
- docs/runbooks/VirtHandlerDaemonSetRolloutFailing.md
Fixing indents and spacing, after testing the conversion script.
> fix indents and spacing

- docs/runbooks/LowVirtAPICount.md
> LowVirtAPICount edits

- docs/runbooks/SSPCommonTemplatesModificationReverted.md
> SSPCommonTemplatesModificationReverted updates

- docs/runbooks/CDIDataImportCronOutdated.md
> Edit CDIDataImportCronOutdated

- docs/runbooks/NoLeadingVirtOperator.md
@apinnick feel free to review when convenient
> Doc rewrites for NoLeadingVirtOperator

- docs/runbooks/VirtControllerRESTErrorsBurst.md
- docs/runbooks/VirtControllerRESTErrorsHigh.md
Signed-off-by: Jiří Herrmann <jherrman@redhat.com>
> Rewrites to VirtControllerRESTErrors* docs

- docs/runbooks/HPPSharingPoolPathWithOS.md
@apinnick please review the changes when convenient
> Doc rewrites to HPPSharingPoolPathWithOS

- docs/runbooks/CnaoNmstateMigration.md
@apinnick , please review the changes when you find some time.
> Doc rewrites for CnaoNmstateMigration

- docs/runbooks/CDIOperatorDown.md
Rewrote the CDIOperatorDown runbook for downstream conversion.
Signed-off-by: davozeni <davozeni@redhat.com>
> Doc rewrites for CDIOperatorDown runbook

- docs/runbooks/CDIStorageProfilesIncomplete.md
Rewrote the CDIStorageProfilesIncomplete runbook for downstream conversion.
Signed-off-by: davozeni <davozeni@redhat.com>
> Doc rewrites for CDIStorageProfilesIncomplete

- docs/runbooks/CDINotReady.md
Changed the runbook to comply with the updated guidelines for script conversion.
Signed-off-by: davozeni <davozeni@redhat.com>
> Doc update for CDINotReady runbook

- docs/runbooks/KubeVirtVMStuckInErrorState.md
- docs/runbooks/KubeVirtVMStuckInMigratingState.md
- docs/runbooks/KubeVirtVMStuckInStartingState.md
Signed-off-by: apinnick2 <apinnick@redhat.com>
> KubeVirtVMStuck edits

- docs/runbooks/NetworkAddonsConfigNotReady.md
> NetworkAddonsConfigNotReady edits

- docs/runbooks/LowKVMNodesCount.md
> LowKVMNodesCount edits

- docs/runbooks/KubevirtHyperconvergedClusterOperatorNMOInUseAlert.md
> KubevirtHyperconvergedClusterOperatorNMOInUseAlert edits

- docs/runbooks/VirtControllerDown.md
@apinnick please review the changes at your convenience.
> Doc rewrites for VirtControllerDown (take two)

- docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
> fix broken comment tag

- docs/runbooks/CDIDataImportCronOutdated.md
- docs/runbooks/CnaoDown.md
- docs/runbooks/HPPNotReady.md
- docs/runbooks/KubeVirtComponentExceedsRequestedCPU.md
- docs/runbooks/KubeVirtComponentExceedsRequestedMemory.md
- docs/runbooks/KubeVirtVMStuckInErrorState.md
- docs/runbooks/KubeVirtVMStuckInStartingState.md
- docs/runbooks/LowKVMNodesCount.md
- docs/runbooks/LowReadyVirtControllersCount.md
- docs/runbooks/LowReadyVirtOperatorsCount.md
- docs/runbooks/LowVirtControllersCount.md
- docs/runbooks/NoLeadingVirtOperator.md
- docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
- docs/runbooks/VMCannotBeEvicted.md
- docs/runbooks/VirtApiRESTErrorsHigh.md
- docs/runbooks/VirtControllerDown.md
> Small fixes to improve rendering

- docs/runbooks/KubeVirtDeprecatedAPIsRequested.md
- docs/runbooks/README.md
This will unblock https://github.com/kubevirt/kubevirt/pull/9724
> Add runbook for KubeVirtDeprecatedAPIsRequested

- .github/workflows/prom-metrics-linter.yaml
- test/metrics/prom-metrics-linter/Dockerfile
- test/metrics/prom-metrics-linter/metric_name_linter.go
1. Fix the github action job trigger to only when pushing new changes to prom-metrics-linter dir
2. Add new lines in the Docker file 
3. Add missing error msg
> Fix metric name linter

- .github/workflows/prom-metrics-linter.yaml
Make metrics linter image to be build by version tag
> Add tags to metric name linter

- docs/runbooks/README.md
- docs/runbooks/VirtualMachineCRCErrors.md
Runbook for alert in PR https://github.com/kubevirt/kubevirt/pull/9741
> Add VirtualMachineCRCErrors runbook

- test/metrics/prom-metrics-linter/README.md
Add a README file for prom-metrics-linter.
> [docs] Add a readme for prom-metrics-linter

- docs/runbooks/VirtualMachineCRCErrors.md
This PR updates `VirtualMachineCRCErrors` runbook to reflect that the alert now aggregates all VMs with issues, so we are adding a script so that users can more easily find which VMs are subject to problems
> Update VirtualMachineCRCErrors runbook to handle aggregated alert

- docs/runbooks/CDIDefaultStorageClassDegraded.md
- docs/runbooks/CDINoDefaultStorageClass.md
CDINoDefaultStorageClass & CDIDefaultStorageClassDegraded.
> Add CDI default storage class alert runbooks

- docs/deprecated_runbooks/VirtualMachineCRCErrors.md
- docs/runbooks/VMStorageClassWarning.md
jira-ticket: https://issues.redhat.com/browse/CNV-35099
jira-ticket: https://issues.redhat.com/browse/CNV-35400
Pending https://github.com/kubevirt/ssp-operator/pull/875
Fixes #
**Checklist**
```release-note
Rename VirtualMachineCRCErrors to VMStorageClassWarning
```
> Rename VirtualMachineCRCErrors to VMStorageClassWarning

- monitoringlinter/analyzer_test.go
- monitoringlinter/cmd/monitoringlinter/main.go
- monitoringlinter/go.mod
In https://github.com/kubevirt/monitoring/pull/221, the monitoring linter was accidentally added with module path `github.com/monitoring/monitoringlinter`. This PR fixes it to `github.com/kubevirt/monitoring/monitoringlinter`.
/cc @nunnatsa 
**Checklist**
```release-note
None
```
> Fix monitoring linter module path

- docs/runbooks/CDIDataImportCronOutdated.md
We made similar adaptations to docs as well, but this was left out:
https://github.com/openshift/openshift-docs/pull/65659
Fixes #
**Checklist**
```release-note
NONE
```
> Include reference to snapshot sources in CDIDataImportCronOutdated

- docs/runbooks/CDIDefaultStorageClassDegraded.md
- docs/runbooks/CDINoDefaultStorageClass.md
- docs/runbooks/CDIStorageProfilesIncomplete.md
- docs/runbooks/HCOInstallationIncomplete.md
- docs/runbooks/KubeMacPoolDuplicateMacsFound.md
- docs/runbooks/KubeVirtCRModified.md
- docs/runbooks/KubeVirtDeprecatedAPIRequested.md
- docs/runbooks/KubeVirtVMIExcessiveMigrations.md
- docs/runbooks/KubevirtVmHighMemoryUsage.md
- docs/runbooks/LowKVMNodesCount.md
- docs/runbooks/LowReadyVirtControllersCount.md
- docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
- docs/runbooks/SingleStackIPv6Unsupported.md
- docs/runbooks/UnsupportedHCOModification.md
- docs/runbooks/VirtApiRESTErrorsBurst.md
- docs/runbooks/VirtApiRESTErrorsHigh.md
- docs/runbooks/VirtControllerRESTErrorsBurst.md
- docs/runbooks/VirtControllerRESTErrorsHigh.md
- docs/runbooks/VirtHandlerRESTErrorsBurst.md
- docs/runbooks/VirtHandlerRESTErrorsHigh.md
- docs/runbooks/VirtOperatorRESTErrorsBurst.md
- docs/runbooks/VirtOperatorRESTErrorsHigh.md
Fix spacing diffs from downstream
Fixes #
**Checklist**
```release-note
NONE
```
> Fix spacing diffs from downstream

- docs/runbooks/CDIDataImportCronOutdated.md
- docs/runbooks/CDIDefaultStorageClassDegraded.md
Improve runbooks docs readability
Fixes #
**Checklist**
```release-note
Improve runbooks docs readability
```
> Improve runbooks docs readability

- LICENSE
- monitoringlinter/analyzer.go
- monitoringlinter/analyzer_test.go
- monitoringlinter/cmd/monitoringlinter/main.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_import.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_registration.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/with_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_import.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_registration.go
- monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/with_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_import.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_registration.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/with_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_import.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_local_name.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_registration.go
- monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/with_local_name.go
- tools/metricsdocs/git.go
- tools/metricsdocs/metricsdocs.go
- tools/metricsdocs/types.go
- tools/runbook-sync-downstream/commitdate.go
- tools/runbook-sync-downstream/main.go
- tools/runbook-sync-downstream/runbook.go
- tools/runbook-sync-downstream/setup.go
- tools/runbook-sync-downstream/worktree.go
**What this PR does**:
Add public copyright license to all files in the repo.
Fixes https://github.com/kubevirt/monitoring/issues/206
Jira-ticket: https://issues.redhat.com/browse/CNV-41504
**Checklist**
```release-note
None
```
> Add public copyright license

- docs/runbooks/CDIDefaultStorageClassDegraded.md
Fixes https://issues.redhat.com/browse/CNV-41549
> CNV-41549 - Fixing a diagnosis step for CDIDefaultStorageClassDegraded

- docs/runbooks/VMStorageClassWarning.md
Add knowledge base link and contact info for downstream
Fixes #
**Checklist**
```release-note
Add downstream links info to VMStorageClassWarning runbook
```
> Add downstream links info to VMStorageClassWarning runbook

- tools/runbook-sync-downstream/main.go
When new changes are added to the runbooks, a new PR is created upstream updating all diffs between runbooks. But an old PR that has not been merged yet would remain open with only a portion of the diffs. This change makes the tool close those outdated PRs.
Fixes #
**Checklist**
```release-note
none
```
> [runbook-sync-downstream] Close outdated PRs

- tools/runbook-sync-downstream/main.go
There was a bug introduced in https://github.com/kubevirt/monitoring/pull/260, where the new PR is also being closed. This PR fixes it.
Fixes #
**Checklist**
```release-note
none
```
> Runbook sync closing recently opened PR

- docs/runbooks/PersistentVolumeFillingUp.md
Add PersistentVolumeFillingUp runbook
Fixes #
**Checklist**
```release-note
Add PersistentVolumeFillingUp runbook
```
> Add PersistentVolumeFillingUp runbook

- docs/deprecated_runbooks/SSPOperatorDown.md
- docs/runbooks/HCOGoldenImageWithNoArchitectureAnnotation.md
- docs/runbooks/HCOGoldenImageWithNoSupportedArchitecture.md
- docs/runbooks/HighNodeCPUFrequency.md
Fixes #
**Checklist**
```release-note
none
```
> Improve runbook docs

- docs/runbooks/GuestVCPUQueueHighCritical.md
- docs/runbooks/GuestVCPUQueueHighWarning.md
- docs/runbooks/HCOGoldenImageWithNoArchitectureAnnotation.md
- docs/runbooks/HCOGoldenImageWithNoSupportedArchitecture.md
- docs/runbooks/HCOMultiArchGoldenImagesDisabled.md
- docs/runbooks/LowVirtControllersCount.md
- docs/runbooks/VirtualMachineStuckInUnhealthyState.md
- docs/runbooks/VirtualMachineStuckOnNode.md
add downstream requested changes
Fixes #
**Checklist**
```release-note
none
```
> Update text new runbooks
