runbooks/VMCannotBeEvicted.md
Signed-off-by: Ezra Silvera <ezra@il.ibm.com>
VMCannotBeEvicted is generated when the eviction strategy of a VM is set to "Live Migration" but the VM is not migratable. 
The PR to generate the Prometheus metrics and alert is in  https://github.com/kubevirt/kubevirt/pull/5392
=> Add runbook for VMCannotBeEvicted

runbooks/VirtAPIDown.md
Signed-off-by: Erkan Erol <eerol@redhat.com>
The namespace of Kubevirt is different in different environments.
- `kubevirt`  in https://kubevirt.io/user-guide/operations/installation/
- `kubevirt-hyperconverged` in hco repo
- `openshift-cnv` in OpenShift Virtualization
This PR adds another step to get the namespace from the cluster and to use it in the diagnosis&mitigation.
=> Make VirtAPIDown environment agnostic

dashboards/grafana/kubevirt-control-plane.json
We have been discussing on the [SIG Scale community meeting](https://docs.google.com/document/d/1d_b2o05FfBG37VwlC2Z1ZArnT9-_AEJoQTe7iKaQZ6I/edit?pli=1) the performance and scalability evaluation of KubeVirt control plane. We have also been discussing about measuring and exporting KubeVirt Performance Metrics https://github.com/kubevirt/kubevirt/issues/5732
Therefore, this PR provides a dashboard with the most relevant metrics related to KubeVirt control plane that we have discussed so far..
The API server metrics are grouped into a few major categories:
- Request Rates and Latencies
- Performance of controller work queues
- Etcd performance
- General process status (Memory/CPU Seconds/File Descriptors/Network)
- Golang status (GC/Memory/GoRotines/Threads)
- Storage operation …
=> [Sig-Scale] dashboard: add kubevirt control plane dashboard

docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
U+201D is not stripped by the shell which makes the command illegible to k8s.
=> drop fancy Unicode quote to make example pastable

dashboards/grafana/kubevirt-control-plane.json
This PR introduced several updates to the KubeVirt control plane Grafana dashboard added in #38.
Since it's hard to actually review the JSON diff, I'll attach screenshots highlighting the main changes:
**1. Organize panels in collapsible rows:**
**2. Add panels for API client metrics, based on the metrics reported by client-go.**
This can help visualize the amount and latency of outgoing API calls from controllers, especially during work queue stress periods:
**3. Modify queries used in several work queue panels**
For example, avoid `sum(rate())` for queue depth metric, and avoid `sum(increase())` for unfinished work metric. This renders visuals that better reflect what's going on. Also added a panel for the `workqueue_work_duration` work duration metric:
**4. Rename some panels to better …
=> Update KubeVirt control plane Grafana dashboard

docs/runbooks/CDIStorageProfilesIncomplete.md, docs/runbooks/README.md
CDIStorageProfilesIncomplete is about CDI not being able to infer info about storage,
to spare the users from providing that info themselves.
=> Add storageprofile incomplete alert runbook

docs/runbooks/OrphanedVirtualMachineInstances.md, docs/runbooks/README.md
Updated OrphanedVirtualMachineImages alert runbook
due to an name change.
Alert name was updated to OrphanedVirtualMachineInstances.
=> Update OrphanedVirtualMachineImages alert name

docs/runbooks/CDIDataImportCronOutdated.md, docs/runbooks/README.md
CDIDataImportCronOutdated is about us not being able to keep os images up to date in the cluster automatically.
=> Add DataImportCron outdated alert runbook

monitoring-guidelines.md
Added `kubernetes_operator_part_of` and
`kubernetes_operator_component` lables that
are required for all new alerts.
=> Added new labels required for alerts

dashboards/openshift/kubevirt-top-consumers.json
Update the Top Consumers dashboard:
1. Fix queries for the memory and memory swap
since they are gauges.
2. Updated the panels order.
3. Updated memory panels to use VMI metrics
instead of container metrics.
=> Update the Top Consumers dashboard

docs/runbooks/HPPSharingPoolPathWithOS.md, docs/runbooks/README.md
HPPSharingPoolPathWithOS is about HPP sharing a filesystem with other critical components (kubelet / OS),
making it possible to cause node disk pressure.
=> Add HPP sharing pool path with OS runbook

docs/runbooks/HPPSharingPoolPathWithOS.md
=> Correct typo in HPPSharingPoolPathWithOS runbook

docs/runbooks/CDIDataImportCronOutdated.md
Explain how to opt-out the automatic delivery of default common data sources to refrain from getting this alarm fired in disconnected clusters.
Signed-off-by: orenc1 <ocohen@redhat.com>
=> Add a note for CDIDataImportCronOutdated in disconnected enviroments

dashboards/grafana/kubevirt-control-plane.json
The original dashboard was not working on OpenShift only on a Kubernetes cluster. This is due to some missing label from the metrics used to populate the `instance` variable. I'm using a generic metric now.
In addition, some charts weren't using the default $datasource variable and some metrics weren't showing up in the dashboard.
I also updated the dashboard, including new metrics related to the Kubernetes API.
I also updated the dashboard, including new metrics (fsync, rtt, and ops) related to the ETCD.
/cc @sradco @zcahana @rthallisey 
Signed-off-by: Marcelo Amaral <marcelo.amaral1@ibm.com>
=> update datasource reference and included new metrics in the grafana kubevirt control-plane dashboard

docs/runbooks/KubevirtHyperconvergedClusterOperatorNMOInUseAlert.md, docs/runbooks/README.md
Adding the runbook of the alert that is being introduced at: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1973
Signed-off-by: orenc1 <ocohen@redhat.com>
=> Add runbook for KubevirtHyperconvergedClusterOperatorNMOInUseAlert

dashboards/openshift/kubevirt-top-consumers.json
This PR modifies the tabels in KubeVirt / Infrastructure Resources / Top Consumers dashboard to use Time Range instead of Period, in order to align with the dashboard's graphs (which use Time Range), and to prevent users from confusing between Period and Time Range. 
The following tables are modified:
* Top Consumers of Memory
* Top Consumers of CPU by virt-launcher Pods
* Top Consumers of Storage Traffic
* Top Consumers of Storage IOPS
* Top Consumers of Network Traffic
*  Top Consumers of vCPU Wait
* Top Consumers of Memory Swap Traffic
In addition, it removes the Period drop-down, which shouldn't be in use after these changes.
Signed-off-by: assafad <aadmi@redhat.com>
=> Use Time Range instead of Period for Top Consumers dashboard tables

docs/runbooks/CDIDataVolumeUnusualRestartCount.md, docs/runbooks/KubeMacPoolDown.md, docs/runbooks/KubeVirtVMIExcessiveMigrations.md, docs/runbooks/OrphanedVirtualMachineInstances.md, docs/runbooks/SSPFailingToReconcile.md, docs/runbooks/SSPOperatorDown.md, docs/runbooks/SSPTemplateValidatorDown.md, docs/runbooks/VirtAPIDown.md
Changed format of downstream CP link to Asciidoc because Kramdoc does not convert links in comments.
=> Fixed format of DS links

monitoring-guidelines.md
Add `operator_health_impact` label to the monitoring-guidelines and remove `infra_alert`.
Signed-off-by: assafad <aadmi@redhat.com>
=> Add `operator_health_impact` label to the monitoring-guidelines

docs/runbooks/KubeVirtDeprecatedAPIRequested.md, docs/runbooks/README.md
Renaming KubeVirtDeprecatedAPIsRequested to KubeVirtDeprecatedAPIRequested avoids confusion about plural/singular use.
See https://github.com/kubevirt/monitoring/pull/172#discussion_r1219942486
=> Rename KubeVirtDeprecatedAPIRequested to singular

test/metrics/prom-metrics-linter/metrics-parser/go.mod, test/metrics/prom-metrics-linter/metrics-parser/go.sum, test/metrics/prom-metrics-linter/metrics-parser/metrics_parser.go
In order to maintain general methods used to send metrics to prom-metrics-linter, we want to move as much code as possible to this monitoring repo.
=> Add metrics parser to metricFamily for prom-metrics-linter

docs/runbooks/KubemacpoolDown.md, docs/runbooks/README.md
Currently, [KubemacpoolDown alert](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/data/monitoring/prom-rule.yaml#L57) has a runbook with the name `KubeMacPoolDown`. This PR copies this runbook to a new runbook which is named correctly.
=> Copy KubemacpoolDown runbook to a correct file name

docs/deprecated_runbooks/KubeVirtVMStuckInErrorState.md, docs/deprecated_runbooks/KubeVirtVMStuckInMigratingState.md, docs/deprecated_runbooks/KubeVirtVMStuckInStartingState.md
Re-add runbooks that were added in https://github.com/kubevirt/monitoring/pull/100, but to the [deprecated_runbooks](https://github.com/kubevirt/monitoring/tree/main/docs/deprecated_runbooks) directory. 
Fixing https://issues.redhat.com/browse/CNV-31006.
=> Re-add runbooks for KubeVirtVMStuckIn${STATE}State alerts

docs/runbooks/VirtualMachineCRCErrors.md
Due to size constraints in documentation, we should prefer using textual output instead of tables
=> Replace output table with text format

docs/runbooks/VirtApiRESTErrorsBurst.md, docs/runbooks/VirtControllerRESTErrorsBurst.md, docs/runbooks/VirtHandlerRESTErrorsBurst.md, docs/runbooks/VirtOperatorRESTErrorsBurst.md
Updated the alert runbooks related to error burst alerts, to indicate the burst in ongoing for the last 5 minutes and perhaps event more.
Fixes #
Fixes: https://issues.redhat.com/browse/CNV-38540
**Checklist**
```release-note
NONE
```
=> Update the error burst alert runbooks

docs/runbooks/LowReadyVirtControllersCount.md
Improve LowReadyVirtControllersCount wording in causes description
Fixes #
**Checklist**
```release-note
Update LowReadyVirtControllersCount causes description
```
=> Update LowReadyVirtControllersCount causes description

.github/workflows/runbook_sync_downstream.yaml, Makefile, tools/runbook-sync-downstream/main.go, tools/runbook-sync-downstream/runbook.go, tools/runbook-sync-downstream/setup.go
Enable automation to sync runbook updates
Fixes https://issues.redhat.com/browse/CNV-41925
**Checklist**
```release-note
NONE
```
=> Enable runbook-sync-downstream automation workflow 

docs/runbooks/CDIDataImportCronOutdated.md, docs/runbooks/CDIDefaultStorageClassDegraded.md, docs/runbooks/CDIMultipleDefaultVirtStorageClasses.md, docs/runbooks/CDINoDefaultStorageClass.md
- Improve and cleanup the runbooks.
- Use `kubectl` `jsonpath` instead of `jq`.
- Align all references to default `virtualization` storage class instead of `KubeVirt`.
**Which issue(s) this PR fixes**:
jira-ticket: https://issues.redhat.com/browse/CNV-37427
**Checklist**
```release-note
Improve CDI alert runbooks
```
=> Improve CDI alert runbooks

docs/runbooks/CDIDataImportCronOutdated.md, docs/runbooks/CDIDefaultStorageClassDegraded.md, docs/runbooks/CDINoDefaultStorageClass.md
Follow-up to #253 fixing @ousleyp comments.
**Which issue(s) this PR fixes**:
jira-ticket: https://issues.redhat.com/browse/CNV-37427
**Checklist**
```release-note
NONE
```
=> Improve CDI alert runbooks clarity

tools/runbook-sync-downstream/main.go, tools/runbook-sync-downstream/templates/deprecated_runbook.tmpl
the sync runbooks automation should update a deprecated runbook content to state that the runbook is deprecated but keep it in the same folder as the others instead of moving it to a deprecated/ directory
https://issues.redhat.com/browse/CNV-45512
Fixes #
**Checklist**
```release-note
none
```
=> Create file with deprecation message for deprecated runbooks

docs/runbooks/VMStorageClassWarning.md
jira-ticket: https://issues.redhat.com/browse/CNV-40925
Fixes #
**Checklist**
```release-note
Update metric in VMStorageClassWarning runbook
```
=> Update metric in VMStorageClassWarning runbook

docs/runbooks/HCOMisconfiguredDescheduler.md
Add a runbook for `HCOMisconfiguredDescheduler`
A [Descheduler](https://github.com/kubernetes-sigs/descheduler) is a Kubernetes application that causes the control plane to re-arrange the workloads in a better way.
It operates every pre-defined period and goes back to sleep after it had performed its job.
The descheduler uses the Kubernetes [eviction API](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/) to evict pods, and receives feedback from `kube-api` whether the eviction request was granted or not.
On the other side, in order to keep VM live and trigger live-migration, KubeVirt handles eviction requests in a custom way and unfortunately a live migration takes time.
So from the descheduler's point of view, `virt-launcher` …
=> Add HCOMisconfiguredDescheduler runbook

tools/metricsdocs/types.go
KubeVirt metrics docs path is now `docs/observability/metrics.md`
Fixes #
**Checklist**
```release-note
none
```
=> Change kubevirt/kubevirt metrics docs path

docs/runbooks/OperatorConditionsUnhealthy.md
Runbook for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3144
Fixes #
**Checklist**
```release-note
Add OperatorConditionsUnhealthy runbook
```
=> Add OperatorConditionsUnhealthy runbook

docs/runbooks/OperatorConditionsUnhealthy.md
Fixes minor wording quibbles in the runbook. Suggested in https://github.com/openshift/runbooks/pull/219
=> Minor tweaks for OperatorConditionsUnhealthy.md

docs/runbooks/HCOMisconfiguredDescheduler.md
Improves the writing style of the runbook, as per https://github.com/openshift/runbooks/pull/213/
=> Writing style tweaks for HCOMisconfiguredDescheduler.md

docs/runbooks/HCOMisconfiguredDescheduler.md
Fix HCOMisconfiguredDescheduler lines length to pass sanity.
```release-note
none
```
=> Fix HCOMisconfiguredDescheduler lines length

docs/runbooks/HAControlPlaneDown.md, docs/runbooks/HighCPUWorkload.md, docs/runbooks/NodeNetworkInterfaceDown.md
Add runbooks for observability controller alerts
- HAControlPlaneDown
- NodeNetworkInterfaceDown
- HighCPUWorkload
/cc @sradco @jherrman
Fixes #
**Checklist**
```release-note
Add runbooks for observability controller alerts
```
=> Add runbooks for observability controller alerts

monitoringlinter/go.mod, monitoringlinter/go.sum
```release-note
Bump go to 1.23.6 for the monitoring linter
```
=> monitoring-linter: bump go to v1.23.6

.github/workflows/prom-metrics-linter.yaml, test/metrics/prom-metrics-linter/Dockerfile
These changes enable building and pushing Docker images for multiple platforms (amd64, arm64, s390x).
As of now, only x86 support is available for the prom-metrics-linter image: https://quay.io/repository/kubevirt/prom-metrics-linter?tab=tags&tag=latest.
This PR introduces changes to enable multi-architecture builds for arm64 and s390x, in addition to x86, using GitHub Actions.
Fixes # #285 
**Checklist**
**Release …
=> Enhance GitHub Actions workflow for multi-platform builds.

test/metrics/prom-metrics-linter/Dockerfile
This modification ensures that the image can be built for various operating systems, not just Linux, by utilizing the appropriate platform variables during the build process.
This PR updates the Dockerfile to dynamically reference the platform architecture using the ${TARGETOS} and ${TARGETARCH} variables instead of the hardcoded linux platform. This change makes the Dockerfile more flexible and adaptable for building images across different operating systems and architectures
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of items …
=> Update Dockerfile to use TARGETOS instead of linux.

test/metrics/prom-metrics-linter/Dockerfile
```release-note
Image build: bump golang to v1.23
```
=> Bump golang base image in the Dockerfile, to 1.23

docs/runbooks/HCOGoldenImageWithNoArchitectureAnnotation.md, docs/runbooks/HCOGoldenImageWithNoSupportedArchitecture.md
Add two new runbooks for new alerts
Added runbooks for the new `HCOGoldenImageWithNoSupportedArchitecture` and the `HCOGoldenImageWithNoArchitectureAnnotation` alerts.
The PR that adds the alert to HCO is here: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3691.
```release-note
Add runbook for the `HCOGoldenImageWithNoSupportedArchitecture` and the `HCOGoldenImageWithNoArchitectureAnnotation` alerts
```
=> Add two new runbooks for new alerts

docs/runbooks/HCOMultiArchGoldenImagesDisabled.md
The `HCOMultiArchGoldenImagesDisabled` alert is triggered When running on a heterogeneous cluster, a cluster with
nodes of different architectures, while the `enableMultiArchBootImageImport` feature gate is disabled in the HyperConverged CR.
This PR adds the runbook for this alert.
**Jira Ticket**:
```jira-ticket
https://issues.redhat.com/browse/CNV-63043
```
```release-note
Added new runbook for the HCOMultiArchGoldenImagesDisabled alert
```
=> Add new runbook for the HCOMultiArchGoldenImagesDisabled alert

docs/runbooks/LowVirtControllersCount.md
Fixes #
**Checklist**
```release-note
none
```
=> Fix pod references in LowVirtControllersCount runbook

docs/runbooks/HCOMultiArchGoldenImagesDisabled.md
We don't need specific downstream commands, they are changed by automation tooling
Fixes #
**Checklist**
```release-note
none
```
=> Remove unnecessary downstream command from HCOMultiArchGoldenImagesDisabled
